### ISSUE TITLE
Could you provide the pretrained backbone file?

### ISSUE THREAD

**Issue by XinghanLi66** [KostasStefanidis/Semantic-Segmentation-Cityscapes#2]
I'm using DeepLabV3plus model with an EfficientNetV2M backbone, working on a segmentation task on Cityscapes dataset. I tried downloading the pretrained EfficientNetV2M weights from kaggle but end up with a layer count mismatch. So where can I find the pretrained weights for EfficientNetV2M, or could you provide it? Thanks in advance!

**Comment by KostasStefanidis** [comment]
The EfficientNetV2M backbone used was the one bultin with the tensorflow package (https://www.tensorflow.org/versions/r2.10/api_docs/python/tf/keras/applications/efficientnet_v2/EfficientNetV2M). In my case I got the source code for EfficientNetV2 to do some modifications to be able to choose the desired output stride of DeepLabV3+ .

**Comment by XinghanLi66** [comment]
Ok many thanks :)
